### ISSUE TITLE
import VuePIXI from 'vue-pixi'

### ISSUE THREAD

**Issue by Sodininkas** [Granipouss/vue-pixi#1]
Do not work, error with first line - import VuePIXI from 'vue-pixi'; modules are declared. using vue 2

**Comment by minonl** [comment]
> Do not work, error with first line - import VuePIXI from 'vue-pixi'; modules are declared. using vue 2

There is no built library under dist folder, so current work around is to build by yourself after npm/yarn installation.
`cd node_modules/vue-pixi; npm install && npm build`
